name: Build

on:
  push:
    paths:
      - '**.yaml'
      - '**.cpp'
      - '**.hpp'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Compile
      run: |
        cmake .
        make pimlico_library -j4
        echo $? > passing.txt

    - name: Update badge
      run: |
        export GIST_TOKEN=${{ secrets.GIST_TOKEN }}
        PASSING=`cat passing.txt`
        python3 .github/badges/update_build_badge.py \
            ${PASSING} \
            2dda5da8e52e2be176c1df0f520d06c5 \
            'pimlico-build-badge.json'
