name: Build

on:
  push:
    paths:
      - '**.cpp'
      - '**.hpp'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Compile
      run: |
        cmake .
        make pimlico_library -j4
