name: Lint

on:
  push:
    paths:
      - '**.cpp'
      - '**.hpp'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@latest
      with:
        cmake-version: '3.16.x'
    - name: Compile
      run: |
        cmake .
        make
