name: Test

on:
  pull_request:
    paths:
      - '**.yaml'
      - '**.cpp'
      - '**.hpp'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure
      run: sudo apt-get install gcovr

    - name: Compile
      run: |
        cmake .
        make test -j4

    - name: Run Test
      continue-on-error: true
      run: ./test/binaries/test

    - name: Evaluate coverage
      run: |
        gcovr \
            --root source/ \
            --object-directory CMakeFiles/ \
            --exclude "/usr*" \
            --exclude "test*" \
            --exclude "/Library*" \
            --delete \
            --print-summary > out.txt
        cat out.txt

        cat out.txt | \
            grep -o 'lines: .*%' | \
            grep -o '[0-9]\+\(\.[0-9]\+\)\?' > coverage.txt

    - name: Update badge
      run: |
        export GIST_TOKEN=${{ secrets.GIST_TOKEN }}
        COVERAGE=`cat coverage.txt`
        python3 .github/badges/update_coverage_badge.py \
            ${COVERAGE} \
            2dda5da8e52e2be176c1df0f520d06c5 \
            'pimlico-coverage-badge.json'
