name: Test

on:
  push:
    paths:
      - '**.yaml'
      - '**.cpp'
      - '**.hpp'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure
      run: sudo apt-get install gcovr

    - name: Compile
      run: |
        cmake .
        make test -j4

    - name: Run Test
      run: ./tests/binaries/test

    - name: Evaluate coverage
      run: |
        gcovr \
            --root source/ \
            --object-directory CMakeFiles/ \
            --exclude "/usr*" \
            --exclude "test*" \
            --exclude "/Library*" \
            -j4 \
            --delete \
            --print-summary > out.txt

        cat out.txt | \
            grep -o 'lines: .*%' | \
            grep -o '[0-9]\+\(\.[0-9]\+\)\?' > coverage.txt
