name: Test

on:
  push:
    paths:
      - '**.cpp'
      - '**.hpp'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Compile
      run: |
        cmake .
        make test -j4

    - name: Run Tests
      run: |
        sudo apt-get install gcovr

        ./tests/binaries/test
        
        gcovr \
            --root source/ \
            --object-directory CMakeFiles/ \
            --exclude "/usr*" \
            --exclude "test*" \
            --exclude "/Library*" \
            -j4 \
            --delete
