binary <int> := '0b' ('0' | '1')+ {
    return std::stoi(__text__, nullptr, 2);
}

octal <int> := '0' ['0' - '7']+ {
    return std::stoi(__text__, nullptr, 8);
}

decimal <int> := '0d'? ['0' - '9']+ {
    return std::stoi(__text_);
}

hexadecimal <int> := '0x' (['0' - '9'] | ['a' - 'f'] | ['A' - 'F'])+ {
    return std::stoi(__text__, nullptr, 16);
}

radix :=
    binary
    decimal
    octal
    hexadecimal
